# Generated by Django 5.1.4 on 2024-12-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='cltsupri.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaSuprimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_entregue', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('setor', models.CharField(max_length=100)),
                ('suprimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='cltsupri.suprimento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='cltsupri.unidade')),
            ],
        ),
    ]
