# Generated by Django 4.2.22 on 2025-08-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suprimento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('impressora', 'Impressora'), ('tv', 'TV'), ('outro', 'Outro')], max_length=50)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='cltsupri.unidade')),
            ],
        ),
    ]
