# Generated by Django 4.2.22 on 2025-08-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0002_alter_suprimento_nome_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(choices=[('impressora', 'Impressora'), ('tv', 'TV'), ('outro', 'Outro')], default='impressora', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
