# Generated by Django 4.2.22 on 2025-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0003_equipamento_nome_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_operacional', models.CharField(blank=True, max_length=200, null=True)),
                ('processador', models.CharField(blank=True, max_length=200, null=True)),
                ('memoria_total', models.FloatField(blank=True, null=True)),
                ('placa_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('fabricante_placa_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('disco', models.CharField(blank=True, max_length=200, null=True)),
                ('tamanho_disco', models.FloatField(blank=True, null=True)),
                ('tempo_off_dias', models.IntegerField(default=0)),
                ('tempo_off_horas', models.IntegerField(default=0)),
                ('tempo_off_minutos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10)),
            ],
        ),
    ]
