# Generated by Django 4.2.22 on 2025-08-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0004_maquina'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo_nome', models.CharField(help_text='Prefixo do nome da máquina para associar', max_length=200, unique=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes', to='cltsupri.unidade')),
            ],
        ),
    ]
