# Generated by Django 4.2.22 on 2025-08-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0005_unidadeassociacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='unidade_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_associadas', to='cltsupri.unidade'),
        ),
    ]
