# Generated by Django 4.2.22 on 2025-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0006_maquina_unidade_associada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fornecedor_associado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ModeloFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(choices=[('ECO', 'ECO'), ('DISTRICOMP', 'DISTRICOMP')], max_length=50)),
            ],
            options={
                'unique_together': {('modelo', 'fornecedor')},
            },
        ),
    ]
