# Generated by Django 4.2.22 on 2025-11-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0007_maquina_fornecedor_associado_modelofornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ConsolidadoMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_maquinas', to='cltsupri.projeto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidados_maquinas', to='cltsupri.unidade')),
            ],
            options={
                'verbose_name': 'Consolidado de Máquinas',
                'verbose_name_plural': 'Consolidados de Máquinas',
                'ordering': ['projeto', 'unidade'],
                'unique_together': {('projeto', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados', to='cltsupri.equipamentocadastro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados_equipamento', to='cltsupri.projeto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados_equipamento', to='cltsupri.unidade')),
            ],
            options={
                'verbose_name': 'Consolidado de Equipamento',
                'verbose_name_plural': 'Consolidados de Equipamentos',
                'ordering': ['projeto', 'unidade', 'equipamento'],
                'unique_together': {('projeto', 'unidade', 'equipamento')},
            },
        ),
    ]
