# Generated by Django 6.0.3 on 2026-04-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0008_equipamentocadastro_equipamento_setor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True, verbose_name='Ticket ID')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('tecnico', models.CharField(max_length=100, verbose_name='Técnico')),
                ('equipamento_marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('equipamento_modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('processador_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Processador')),
                ('processador_socket', models.CharField(blank=True, max_length=50, null=True, verbose_name='Socket do Processador')),
                ('processador_estado', models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20)),
                ('ram_tipo', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('Não contém', 'Não contém RAM')], default='DDR4', max_length=20)),
                ('ram_qtd_pentes', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Pentes')),
                ('ram_pentes_detalhes', models.JSONField(blank=True, default=list, help_text="Lista de dicionários [{capacidade: X, estado: 'Bom'}]")),
                ('armazenamento_tipo', models.CharField(choices=[('HD', 'HD'), ('SSD', 'SSD'), ('NVMe', 'NVMe'), ('Não contém', 'Não contém')], default='SSD', max_length=20)),
                ('armazenamento_capacidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacidade (ex: 500GB)')),
                ('armazenamento_estado', models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20)),
                ('placa_mae_estado', models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20)),
                ('placa_video_estado', models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20)),
                ('fonte_tipo', models.CharField(choices=[('ATX', 'ATX'), ('Slim', 'Slim'), ('Não contém', 'Não contém')], default='ATX', max_length=20)),
                ('fonte_estado', models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20)),
                ('cooler_estado', models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20)),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Automático')),
            ],
        ),
    ]
