# Generated by Django 6.0.3 on 2026-04-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0009_ticketmanutencao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmanutencao',
            name='placa_video_estado',
        ),
    ]
