# Generated by Django 6.0.3 on 2026-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0010_remove_ticketmanutencao_placa_video_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='equipamento_modelo',
            field=models.CharField(choices=[('Grande', 'Grande'), ('Slim', 'Slim')], default='Grande', max_length=100, verbose_name='Modelo do Gabinete'),
        ),
    ]
