# Generated by Django 6.0.3 on 2026-04-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0011_alter_ticketmanutencao_equipamento_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmanutencao',
            name='gabinete_estado',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim'), ('Não contém', 'Não contém')], default='Bom', max_length=20),
        ),
    ]
