# Generated by Django 6.0.3 on 2026-04-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0012_ticketmanutencao_gabinete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='gabinete_estado',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Ruim', 'Ruim')], default='Bom', max_length=20),
        ),
    ]
