# Generated by Django 6.0.3 on 2026-04-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0013_alter_ticketmanutencao_gabinete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmanutencao',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patrimônio'),
        ),
    ]
