# Generated by Django 6.0.3 on 2026-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0015_ticketmanutencao_ram_ausente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='ram_tipo',
            field=models.CharField(blank=True, choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=20, null=True, verbose_name='Tecnologia (DDR)'),
        ),
    ]
