# Generated by Django 6.0.3 on 2026-04-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0016_alter_ticketmanutencao_ram_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='ram_tipo',
            field=models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], default='DDR4', max_length=20, verbose_name='Tecnologia (DDR)'),
        ),
    ]
