# Generated by Django 6.0.3 on 2026-04-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0017_alter_ticketmanutencao_ram_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmanutencao',
            name='tipo_equipamento',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Estabilizador', 'Estabilizador'), ('Nobreak', 'Nobreak')], default='Desktop', max_length=50, verbose_name='Tipo de Equipamento'),
        ),
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='equipamento_modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
    ]
