# Generated by Django 6.0.3 on 2026-04-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0018_ticketmanutencao_tipo_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmanutencao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Técnico'),
        ),
        migrations.AddField(
            model_name='ticketmanutencao',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('AGUARDANDO PEÇAS', 'Aguardando Peças'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
    ]
