# Generated by Django 4.2.29 on 2026-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0019_ticketmanutencao_observacoes_ticketmanutencao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('AGUARDANDO PEÇAS', 'Aguardando Peças'), ('FINALIZADO', 'Finalizado'), ('CONDENADO', 'Condenado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='tipo_equipamento',
            field=models.CharField(choices=[('Gabinete', 'Gabinete'), ('Monitor', 'Monitor'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Estabilizador', 'Estabilizador'), ('Nobreak', 'Nobreak')], default='Gabinete', max_length=50, verbose_name='Tipo de Equipamento'),
        ),
    ]
