# Generated by Django 4.2.29 on 2026-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0020_rename_desktop_to_gabinete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmanutencao',
            name='impressora_tipo',
            field=models.CharField(blank=True, choices=[('Comum', 'Comum'), ('Multifuncional', 'Multifuncional')], max_length=20, null=True, verbose_name='Tipo de Impressora'),
        ),
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='tipo_equipamento',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Impressora', 'Impressora'), ('Monitor', 'Monitor'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('Estabilizador', 'Estabilizador'), ('Nobreak', 'Nobreak')], default='Desktop', max_length=50, verbose_name='Tipo de Equipamento'),
        ),
    ]
