# Generated by Django 4.2.29 on 2026-04-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0021_add_impressora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('AGUARDANDO PEÇAS', 'Aguardando Peças'), ('ENV. ASS. TECNICA', 'Enviado Ass. Técnica'), ('FINALIZADO', 'Finalizado'), ('CONDENADO', 'Condenado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticketmanutencao',
            name='tipo_equipamento',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Estabilizador', 'Estabilizador'), ('Impressora', 'Impressora'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse'), ('Nobreak', 'Nobreak'), ('Teclado', 'Teclado')], default='Desktop', max_length=50, verbose_name='Tipo de Equipamento'),
        ),
    ]
