# Generated by Django 4.2.29 on 2026-04-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltsupri', '0022_add_status_ass_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='suprimento',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. Mínima'),
        ),
    ]
