services:
  django:
    build: .
    container_name: django_suprimentos
    command: gunicorn controlesuprimentos.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
